const CardsData = [
  {
    id: 1,
    name: "AlphaTauri Men Hoodie",
    image:
      "https://assets.alphatauri.com/images/f_auto,q_auto,w_220,c_scale,dpr_3.0,e_sharpen:100/t_product-list/products/2022/AW22/PDP/ATA22546_32_4/Heavyweight-Logo-Hoodie-SCOHO-V2-Y6-02.jpg",
    catagory: "Hoodies",
    description: "",
    size: "XL",
    color: "White",
    price: 60,
    stock: "In Stock",
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 2,
    name: "Unisex Red Hoodie",
    image:
      "https://cdn.shopify.com/s/files/1/0301/5131/1495/products/deadpoollogohoodie1_2048x2048.jpg?v=1658320237",
    catagory: "Hoodies",
    description: "",
    size: "LG",
    color: "Red",
    price: 40,
    stock: "In Stock",
    rating: "4.0",
    qnty: 0,
  },
  {
    id: 3,
    name: "Daraz Men Hoodie",
    image: "https://static-01.daraz.pk/p/ecfac275d12ccfaee418efbdccd5bebb.jpg",
    catagory: "Hoodies",
    description: "",
    size: "MD",
    color: "Blue",
    price: 45,
    stock: "In Stock",
    rating: "4.8",
    qnty: 0,
  },
  {
    id: 4,
    name: "Faded Jeans",
    image:
      "https://www.collinsdictionary.com/images/full/jeans_96398333_1000.jpg",
    catagory: "Jeans",
    description: "",
    size: "LG",
    color: "Blue",
    price: 30,
    stock: "In Stock",
    rating: "3.6",
    qnty: 0,
  },
  {
    id: 5,
    name: "Black Jeans",
    image:
      "https://5.imimg.com/data5/PP/NO/NL/SELLER-86168094/pp-high-quality-knitted-fabric-pure-black-jeans-for-mens-250x250.jpeg",
    catagory: "Jeans",
    description: "",
    size: "SM",
    color: "Black",
    price: 50,
    stock: "In Stock",
    rating: "4.9",
    qnty: 0,
  },
  {
    id: 6,
    name: "Levis White Jeans",
    image:
      "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1616093887-madewell-1616093879.jpg?crop=1xw:1xh;center,top&resize=480:*",
    catagory: "Jeans",
    description: "",
    size: "MD",
    color: "White",
    price: 45,
    stock: "In Stock",
    rating: "4.2",
    qnty: 0,
  },
  {
    id: 7,
    name: "Slim Fit Black T-shirt",
    image:
      "https://lp2.hm.com/hmgoepprod?set=source[/40/71/4071b4a39844344e1de770b4a494ba7e3078219d.jpg],origin[dam],category[men_tshirtstanks_shortsleeve],type[DESCRIPTIVESTILLLIFE],res[w],hmver[2]&call=url[file:/product/main]",
    catagory: "T-shirt",
    description: "",
    size: "LG",
    color: "Black",
    price: 20,
    stock: "In Stock",
    rating: "4.5",
    qnty: 0,
  },
  {
    id: 8,
    name: "Regular fit T-shirt",
    image:
      "https://dictionary.cambridge.org/images/thumb/Tshirt_noun_001_18267.jpg?version=5.0.274",
    catagory: "T-shirt",
    description: "",
    size: "SM",
    color: "Blue",
    price: 25,
    stock: "In Stock",
    rating: "3.8",
    qnty: 0,
  },
  {
    id: 9,
    name: "H&M T-shirt",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVHnlbX64KPSB3FBHfSSg8YmSW-SbDP0-weA&usqp=CAU",
    catagory: "T-shirt",
    description: "",
    size: "XL",
    color: "Yellow",
    price: 29,
    stock: "In Stock",
    rating: "5.0",
    qnty: 0,
  },
];

export default CardsData;
